### ISSUE TITLE
hello,thank you share,

### ISSUE THREAD

**Issue by y377** [ericdaugherty/dnsdigger#1]
How to use it?
```

[root@localhost ~]# cd dnsdigger
[root@localhost dnsdigger]# ls
dns.go  dns_test.go  go.mod  go.sum  LICENSE  README.md
[root@localhost dnsdigger]# ./dns.go
-bash: ./dns.go: Permission denied
[root@localhost dnsdigger]# chmod +x dns.go
[root@localhost dnsdigger]# ./dns.go
./dns.go: line 1: package: command not found
./dns.go: line 3: syntax error near unexpected token `newline'
./dns.go: line 3: `import ('
[root@localhost dnsdigger]# ls
dns.go  dns_test.go  go.mod  go.sum  LICENSE  README.md
[root@localhost dnsdigger]# cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)
[root@localhost dnsdigger]#
```

**Comment by ericdaugherty** [comment]
This is setup as a library, not a command line tool. You need to setup your own project and import this to use it.

**Comment by y377** [comment]
ok.thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Eric ***@***.***&gt;; 
发送时间: 2021年4月20日(星期二) 凌晨1:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ericdaugherty/dnsdigger] hello,thank you share, (#1)





 
This is setup as a library, not a command line tool. You need to setup your own project and import this to use it.
